# Generated by Django 4.0.4 on 2022-04-19 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=75)),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('data_upload', models.DateField(default=datetime.datetime.now)),
                ('link_arquivo', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('data_upload',),
            },
        ),
    ]
