# Generated by Django 4.0.4 on 2022-04-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiado',
            new_name='Arquivos',
        ),
    ]
